### PR TITLE
Tests to set the goal

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
@yegor256 I believe we have to specify the main goal of the demu  utility and on which level it is going to work.
I've added two tests:
1. DeMu converts pure `eo` program with `cage` to a pure `eo` program without `cage`.
2. DeMu converts already optimized `xmir` of the same program to `xmir` without cage.

As far as I know, our aim to remove `cage` from already optimized `xmir`. But I want to know for sure. Please, give some comments and I will remove one of the tests from that PR.

Closes: #2

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Have a look, please

**Comment by yegor256** [comment]
@volodya-lombrozo of course, the DeMu tool should accept _only_ `.xmir` files. However, keep in mind that it will be very convenient for you to have tests written in EO, not in XMIR.

**Comment by volodya-lombrozo** [comment]
@yegor256 I've removed redundant tests. Can you check and merge, please?

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
